apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: frxotk92s-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/frxotk92s-dotnet-basic